import { v4 as uuidv4 } from "uuid"; 

function chillHop() {
    return [

        {
            name:"ovem Pan FM São Paulo ao vivo",
            artist: "ovem Pan FM São Paulo ao vivo",
            cover: "https://img.freepik.com/foto-gratis/microfono-moderno_144627-41309.jpg",
            id: uuidv4(),
            color: ["#F24933", "#F9B437"],
            audio: "https://19293.live.streamtheworld.com/JP_SP_FMAAC_SC",
            active: true,
        },
        {
            name:"Radio Joven pan",
            artist: "Radio Joven pan",
            cover: "https://img.freepik.com/foto-gratis/microfono-moderno_144627-41309.jpg",
            id: uuidv4(),
            color: ["#D7B0D5", "#CBDFE0"],
            audio: "https://14553.live.streamtheworld.com/JP_SP_FMAAC_SC",
            active: false,
        },
        {
            name:"Radio metropolitana",
            artist: "Radio metropolitana",
            cover: "https://img.freepik.com/foto-gratis/microfono-moderno_144627-41309.jpg",
            id: uuidv4(),
            color: ["#1D2731", "#F17E76"],
            audio: "https://f41.fabricahost.com.br/metropolitana985sp?f=1662688105Nd6cf9c3326980e6d87662762412f3bb0&r=aHR0cHM6Ly9yYWRpb3Nhb3Zpdm8ubmV0Lw==",
            active: false,
        },
        {
            name:"los 40 principales",
            artist: "los 40 principales",
            cover: "https://img.freepik.com/vector-gratis/ilustracion-realista-auriculares-inalambricos_1284-20763.jpg",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "https://26423.live.streamtheworld.com/LOS40_MEXICO_SC",
            active: false,
        },
        {
            name:"Magia 101fm",
            artist: "Magia 101fm",
            cover: "https://img.freepik.com/vector-gratis/ilustracion-realista-auriculares-inalambricos_1284-20763.jpg",
            id: uuidv4(),
            color: ["#845648","#FDFBDF"],
            audio: "https://magia101.streaming.radiogrupo.com/",
            active: false,
        },
        {
            name:"Alfa radio",
            artist: "Alfa radio",
            cover: "https://img.freepik.com/vector-gratis/ilustracion-realista-auriculares-inalambricos_1284-20763.jpg",
            id: uuidv4(),
            color: ["#578CCE", "#E9D6D0"],
            audio: "https://20843.live.streamtheworld.com/XHFAJ_FMAAC_SC",
            active: false,
        },
        {
            name:"Stereo vision",
            artist: "Stereo vision",
            cover: "https://img.freepik.com/foto-gratis/microfono-auriculares-espacio-copiar_23-2148681150.jpg",
            id: uuidv4(),
            color: ["#191516", "#82698E"],
            audio: "https://live.turadio.stream:7009/stream/1/",
            active: false,
        },
        {
            name:"Radio columbia",
            artist: "Radio columbia",
            cover: "https://img.freepik.com/foto-gratis/microfono-auriculares-espacio-copiar_23-2148681150.jpg",
            id: uuidv4(),
            color: ["#7BC8DD", "#D64A59"],
            audio: "https://streams.radio.co/s419eaa350/listen",
            active: false,
        },
        {
            name:"Super 100 stereo",
            artist: "Super 100 stereo",
            cover: "https://img.freepik.com/foto-gratis/microfono-audio-estilo-retro_93675-128264.jpg",
            id: uuidv4(),
            color: ["#FDE1A9", "#A46874"],
            audio: "https://20833.live.streamtheworld.com/SUPER100_SC",
            active: false,
        },
        {
            name:"Los 40 105fm",
            artist: "Los 40 105fm",
            cover: "https://img.freepik.com/vector-gratis/radio-plana-retro-ilustrada_23-2148812864.jpg",
            id: uuidv4(),
            color: ["#FDE1A9", "#A46874"],
            audio: "https://27063.live.streamtheworld.com/LOS40_ARGENTINA_SC",
            active: false,
        },
        {
            name:"Mucha radiofm",
            artist: "Mucha radiofm",
            cover: "https://img.freepik.com/vector-gratis/radio-plana-retro-ilustrada_23-2148812864.jpg",
            id: uuidv4(),
            color: ["#FDE1A9", "#A46874"],
            audio: "https://us-b5-p-e-kj2-audio.cdn.mdstrm.com/live-audio-aw-bkp/60a2765c40105808346c569f",
            active: false,
        },
        {
            name:"Radio bio bio",
            artist: "Radio bio bio",
            cover: "https://img.freepik.com/foto-gratis/fondo-musica-o-podcast-auriculares-taza-cafe-mesa-azul-plana-vista-superior-plana_501050-983.jpg",
            id: uuidv4(),
            color: ["#FDE1A9", "#A46874"],
            audio: "https://unlimited5-us.dps.live/biobiosantiago/mp3/icecast.audio",
            active: false,
        },
        {
            name:"Radio corazonfm",
            artist: "Radio corazonfm",
            cover: "https://img.freepik.com/foto-gratis/fondo-musica-o-podcast-auriculares-taza-cafe-mesa-azul-plana-vista-superior-plana_501050-983.jpg",
            id: uuidv4(),
            color: ["#FDE1A9", "#A46874"],
            audio: "https://26503.live.streamtheworld.com/CORAZON_SC",
            active: false,
        },
        {
            name:"Caracol Radio",
            artist: "Caracol Radio",
            cover: "https://img.freepik.com/psd-gratis/ilustracion-3d-representacion-podcast-minimalista-trazado-recorte-auriculares-microfono_1419-2303.jpg",
            id: uuidv4(),
            color: ["#FDE1A9", "#A46874"],
            audio: "https://26583.live.streamtheworld.com/CARACOL_RADIOAAC_SC",
            active: false,
        },
        {
            name:"La fm",
            artist: "La fm",
            cover: "https://img.freepik.com/psd-gratis/ilustracion-3d-representacion-podcast-minimalista-trazado-recorte-auriculares-microfono_1419-2303.jpg",
            id: uuidv4(),
            color: ["#FDE1A9", "#A46874"],
            audio: "https://18693.live.streamtheworld.com/LA_FM_BOGAAC_SC",
            active: false,
        },
        {
            name:"Mix radio fm",
            artist: "Mix radio fm",
            cover: "https://img.freepik.com/psd-gratis/ilustracion-3d-representacion-podcast-minimalista-trazado-recorte-auriculares-microfono_1419-2303.jpg",
            id: uuidv4(),
            color: ["#FDE1A9", "#A46874"],
            audio: "https://24083.live.streamtheworld.com/MIX_BOGOTAAAC_SC",
            active: false,
        },
        {
            name:"Rock and Pop",
            artist: "Rock and Pop",
            cover: "https://img.freepik.com/psd-gratis/ilustracion-3d-trazado-recorte-microfono-rojo_1419-2307.jpg",
            id: uuidv4(),
            color: ["#FDE1A9", "#A46874"],
            audio: "https://s4.yesstreaming.net:17044/stream/1/",
            active: false,
        },
        {
            name:"Radio universal",
            artist: "Radio universal",
            cover: "https://img.freepik.com/psd-gratis/ilustracion-3d-minimalista-microfono-telefono-celular-trazado-recorte-podcast_1419-2302.jpg",
            id: uuidv4(),
            color: ["#FDE1A9", "#A46874"],
            audio: "https://radio.970universal.com:8012/stream/1/",
            active: false,
        },
        {
            name:"El espectador",
            artist: "El espectador",
            cover: "https://img.freepik.com/psd-gratis/ilustracion-3d-minimalista-microfono-telefono-celular-trazado-recorte-podcast_1419-2302.jpg",
            id: uuidv4(),
            color: ["#FDE1A9", "#A46874"],
            audio: "https://espectador1.net.com.uy:8122/stream/",
            active: false,
        },
        {
            name:"Ritmo romantica",
            artist: "Ritmo romantica",
            cover: "https://img.freepik.com/foto-gratis/grabacion-estereo-inalambrico-icono-humana_1232-3551.jpg",
            id: uuidv4(),
            color: ["#FDE1A9", "#A46874"],
            audio: "https://18513.live.streamtheworld.com/CRP_RIT_SC?csegid=20001&dist=20001&ttag=20001",
            active: false,
        },
        {
            name:"Radio existosa",
            artist: "Radio existosa",
            cover: "https://img.freepik.com/foto-gratis/grabacion-estereo-inalambrico-icono-humana_1232-3551.jpg",
            id: uuidv4(),
            color: ["#FDE1A9", "#A46874"],
            audio: "https://7.innovatestream.pe:2020/stream/exitosaoficial/stream/1/",
            active: false,
        },
        {
            name:"Las40 fm",
            artist: "Las40 fm",
            cover: "https://img.freepik.com/psd-gratis/ilustracion-representacion-3d-herramienta-podcast-auriculares_32991-861.jpg",
            id: uuidv4(),
            color: ["#FDE1A9", "#A46874"],
            audio: "https://25643.live.streamtheworld.com/LOS40_SC",
            active: false,
        },
        {
            name:"Onda latina",
            artist: "Onda latina",
            cover: "https://img.freepik.com/psd-gratis/ilustracion-representacion-3d-herramienta-podcast-auriculares_32991-861.jpg",
            id: uuidv4(),
            color: ["#FDE1A9", "#A46874"],
            audio: "https://cervera.eldialdigital.com:21131/stream",
            active: false,
        },
        {
            name:"Skyrock FM",
            artist: "BSkyrock FM",
            cover: "https://img.freepik.com/foto-gratis/microfono-profesional-grabacion-sonido-fotografia-macro_169016-23351.jpg",
            id: uuidv4(),
            color: ["#FDE1A9", "#A46874"],
            audio: "https://icecast.skyrock.net/s/natio_mp3_128k?tvr_name=ecouterradioenligne&tvr_section1=128mp3",
            active: false,
        },
        {
            name:"Swigg Radio",
            artist: "Swigg Radio",
            cover: "https://img.freepik.com/foto-gratis/microfono-profesional-grabacion-sonido-fotografia-macro_169016-23351.jpg",
            id: uuidv4(),
            color: ["#FDE1A9", "#A46874"],
            audio: "https://start-adofm.ice.infomaniak.ch/start-adofm-high.mp3",
            active: false,
        },
        {
            name:"Hit West",
            artist: "Hit West",
            cover: "https://img.freepik.com/foto-gratis/microfono-profesional-grabacion-sonido-fotografia-macro_169016-23351.jpg",
            id: uuidv4(),
            color: ["#FDE1A9", "#A46874"],
            audio: "https://hitwest.ice.infomaniak.ch/hitwest-high.mp3",
            active: false,
        },
        {
            name:"RDS radio",
            artist: "RDS radio",
            cover: "https://img.freepik.com/foto-gratis/3d-render-microfono-retro-pierna-corta-soporte-auriculares-diseno-ilustracion-3d_460848-10407.jpg",
            id: uuidv4(),
            color: ["#FDE1A9", "#A46874"],
            audio: "https://icstream.rds.radio/rds",
            active: false,
        },
        {
            name:"Kis kis fm",
            artist: "Kis kis fm",
            cover: "https://img.freepik.com/foto-gratis/3d-render-microfono-retro-pierna-corta-soporte-auriculares-diseno-ilustracion-3d_460848-10407.jpg",
            id: uuidv4(),
            color: ["#FDE1A9", "#A46874"],
            audio: "https://ice06.fluidstream.net/KissKiss.mp3",
            active: false,
        },
        {
            name:"Radio Rfm",
            artist: "Radio Rfm",
            cover: "https://img.freepik.com/vector-gratis/auriculares-radio-microfono-letreros-neon_1262-19593.jpg",
            id: uuidv4(),
            color: ["#FDE1A9", "#A46874"],
            audio: "https://25653.live.streamtheworld.com/RFM_SC",
            active: false,
        },
        {
            name:"Radio santiago",
            artist: "Radio santiago",
            cover: "https://img.freepik.com/vector-gratis/auriculares-radio-microfono-letreros-neon_1262-19593.jpg",
            id: uuidv4(),
            color: ["#FDE1A9", "#A46874"],
            audio: "https://eu6.fastcast4u.com/proxy/dzuigafo?mp=/stream",
            active: false,
        },
        {
            name:"Herat radio",
            artist: "Herat radio",
            cover: "https://img.freepik.com/vector-gratis/icono-vector-realista-conjunto-microfonos-musica-estilo-antiguo-vintage-plata-negro-oro-isla_134830-1392.jpg",
            id: uuidv4(),
            color: ["#FDE1A9", "#A46874"],
            audio: "https://media-ice.musicradio.com/HeartLondonMP3",
            active: false,
        },
        {
            name:"Caoital fm",
            artist: "Caoital fm",
            cover: "https://img.freepik.com/vector-gratis/icono-vector-realista-conjunto-microfonos-musica-estilo-antiguo-vintage-plata-negro-oro-isla_134830-1392.jpg",
            id: uuidv4(),
            color: ["#FDE1A9", "#A46874"],
            audio: "https://media-ice.musicradio.com/CapitalLiverpoolMP3",
            active: false,
        },
        {
            name:"Metro fm",
            artist: "Metro fm",
            cover: "https://img.freepik.com/vector-gratis/fondo-dia-mundial-radio-dibujado-mano-plana-presentadores_23-2148792698.jpg",
            id: uuidv4(),
            color: ["#FDE1A9", "#A46874"],
            audio: "https://20133.live.streamtheworld.com/METROFM_SC",
            active: false,
        },
        {
            name:"Jozi fm",
            artist: "Jozi fm",
            cover: "https://img.freepik.com/vector-gratis/fondo-dia-mundial-radio-dibujado-mano-plana-presentadores_23-2148792698.jpg",
            id: uuidv4(),
            color: ["#FDE1A9", "#A46874"],
            audio: "https://edge.iono.fm/xice/51_medium.aac",
            active: false,
        },
        {
            name:"Sunshine FM",
            artist: "Sunshine FM",
            cover: "https://img.freepik.com/foto-gratis/pequeno-receptor-radio-transmision-retro_23-2148695311.jpg",
            id: uuidv4(),
            color: ["#FDE1A9", "#A46874"],
            audio: "https://23203.live.streamtheworld.com/4SFM_SC",
            active: false,
        },
        {
            name:"98.9 fm",
            artist: "98.9 fm",
            cover: "https://img.freepik.com/foto-gratis/pequeno-receptor-radio-transmision-retro_23-2148695311.jpg",
            id: uuidv4(),
            color: ["#FDE1A9", "#A46874"],
            audio: "https://live-stream.bimacreative.com.au/",
            active: false,
        },
        {
            name:"Radio Zu",
            artist: "Radio Zu",
            cover: "https://img.freepik.com/vector-gratis/plantilla-marco-neon-aire_23-2148775654.jpg",
            id: uuidv4(),
            color: ["#FDE1A9", "#A46874"],
            audio: "https://live4ro.antenaplay.ro/radiozu/radiozu-48000.m3u8",
            active: false,
        },
        {
            name:"Radio Europa",
            artist: "Radio Europa",
            cover: "https://img.freepik.com/vector-gratis/plantilla-marco-neon-aire_23-2148775654.jpg",
            id: uuidv4(),
            color: ["#FDE1A9", "#A46874"],
            audio: "https://astreaming.edi.ro:8443/EuropaFM_aac",
            active: false,
        },
       }, 
}

export default chillHop;


